# Generated by Django 5.2.17 on 2026-09-23 16:15

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models

import tickets.validators


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Agent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(help_text="Customer's name.", max_length=200)),
                (
                    "email",
                    models.EmailField(
                        help_text="Customer email addresses must be unique, ignoring case.",
                        max_length=254,
                    ),
                ),
                (
                    "company",
                    models.CharField(
                        blank=True, help_text="Optional company name.", max_length=200
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        django.db.models.functions.text.Lower("email"),
                        name="customer_email_ci_unique",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        help_text="Short summary of the support request.", max_length=200
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Describe the issue and what help is needed."),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("in_progress", "In progress"),
                            ("resolved", "Resolved"),
                            ("closed", "Closed"),
                        ],
                        default="open",
                        help_text=(
                            "Save the first comment with Save and continue editing, "
                            "then set Resolved. Closed tickets cannot reopen."
                        ),
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "Low"), (2, "Normal"), (3, "High")],
                        default=2,
                        help_text="Low, Normal, or High urgency; High sorts first.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assignees",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Assign agents, or leave blank for the unassigned queue.",
                        related_name="tickets",
                        to="tickets.agent",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        help_text="Customer who made this request.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tickets",
                        to="tickets.customer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "body",
                    models.TextField(
                        help_text="Record the support update before resolving the ticket."
                    ),
                ),
                (
                    "attachment",
                    models.FileField(
                        blank=True,
                        help_text="Optional PDF, PNG, or JPEG file, up to 5 MiB.",
                        upload_to=tickets.validators.attachment_path,
                        validators=[tickets.validators.validate_attachment],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="tickets.ticket",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(fields=["status", "created_at"], name="ticket_queue_index"),
        ),
        migrations.AddConstraint(
            model_name="ticket",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["open", "in_progress", "resolved", "closed"])),
                name="ticket_valid_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="ticket",
            constraint=models.CheckConstraint(
                condition=models.Q(("priority__in", [1, 2, 3])), name="ticket_valid_priority"
            ),
        ),
    ]
