# Generated by Django 5.2.17 on 2026-09-23 21:37

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tickets", "0002_roles"),
    ]

    operations = [
        migrations.AlterConstraint(
            model_name="customer",
            name="customer_email_ci_unique",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("email"),
                name="customer_email_ci_unique",
                violation_error_message="A customer with this email address already exists.",
            ),
        ),
    ]
