# Generated by Django 5.2.17 on 2026-09-24 09:39

from django.db import migrations, models

import tickets.validators


class Migration(migrations.Migration):
    dependencies = [
        ("tickets", "0003_customer_email_error_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="attachment",
            field=models.FileField(
                blank=True,
                help_text="Optional PDF, PNG, or JPEG file, up to 3 MiB.",
                upload_to=tickets.validators.attachment_path,
                validators=[tickets.validators.validate_attachment],
            ),
        ),
    ]
