# Generated by Django 5.2.17 on 2026-09-24 19:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tickets", "0005_customer_comment_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Open"),
                    ("in_progress", "In progress"),
                    ("resolved", "Resolved"),
                    ("closed", "Closed"),
                ],
                default="open",
                help_text=(
                    "Before resolving, save a comment while status is Open or In progress "
                    "using Save and continue editing. Then set Resolved. "
                    "Closed tickets cannot reopen."
                ),
                max_length=20,
            ),
        ),
    ]
